### ISSUE TITLE
Luciano Contato

### ISSUE THREAD

**Issue by pabloruan0710** [luciano-work/WebPrintZebra#1]
Olá luciano, sei que aqui não é o lugar corretor para postar isso, mas não achei outro local para entrar em contato com você, vi que recentemente você teve um problema com a biblioteca whats-api de bloquear o numero, também estou com mesmo problema.. você conseguiu solucionar o seu?

**Comment by lannodev** [comment]
Olá Pablo,
Eu usei um bom tempo o whats-api mas infelizmente o Facebook esta tentando de qualquer forma driblar os seus recursos, como criptografia, bloqueios, etc...
O problema é que o pessoal que desenvolveu não tem uma solução eficaz, dizem que é problema de "flow" no código e com isso estamos sempre correndo o risco de ter o numero bloqueado.

Estou usando o Telegram, é open source e tem uma excelente documentação.
Faça o mesmo, migre para o Telegram que é oficial. 😊
